### ISSUE TITLE
[FEAT] - Plutono PluginDefinition

### ISSUE THREAD

**Issue by IvoGoman** [cloudoperators/greenhouse#105]
### Priority

(Medium) I'm annoyed but I'll live

### Description

Organization administrators can deploy a Plutono _Plugin_ into their namespace on the Greenhouse central cluster.
Plutono comes with a set of pre-installed kube-monitoring dashboards and has the capability to load custom dashboards from a git repo.

Acceptance criteria:

- Plugin contains
   1. Single Plutono instance
   2. Configuration for Prometheus datasources
   3. Dashboards
      - Dashboards for kube-metrics pre-installed, use Plutono built-in capabilities to import/export dashboards
      - Advanced: Automatically sync dashboards from a customer repo.

- Ingress configured per convention
      1. plutono.<org_name>.greenhouse.\<TLD\> (with OIDC)
      2. plutono-internal.<org_name>.greenhouse.\<TLD\> (w/o OIDC)

cc @artherd42 @richardtief

**Comment by richardtief** [comment]
Already here: https://github.com/cloudoperators/greenhouse-extensions/issues/38
