### ISSUE TITLE
[FEAT] - PluginDefinition & Plugin Admin view

### ISSUE THREAD

**Issue by IvoGoman** [cloudoperators/greenhouse#108]
### Priority

(Medium) I'm annoyed but I'll live

### Description

In the organization tab all administrators and members can see a list of available _PluginDefinitions_. See the _PluginDefinition_ CRD.

MVP:

- List of _PluginDefinitions_ showing the .metadata.name, .spec.description, .spec.version

Vision:

- Include detailed _PluginDefinition_ description. Either include link to an external source like the PluginDefinition catalog on the website, or include via configmap that is deployed to the cluster.
- Organization administrators can click a _PluginDefinition_ to start the wizard to instantiate it (creating a _Plugin_)

**Comment by uwe-mayer** [comment]
See https://github.com/cloudoperators/greenhouse/pull/142 for ongoing work

**Comment by uwe-mayer** [comment]
See https://github.com/cloudoperators/greenhouse/issues/152 for MVP acceptance criteria

**Comment by uwe-mayer** [comment]
Closing in favour of:

https://github.com/cloudoperators/greenhouse/issues/288
