### ISSUE TITLE
🐛 [BUG] - dev-env image build failing

### ISSUE THREAD

**Issue by uwe-mayer** [cloudoperators/greenhouse#129]
### Priority

(Medium) I'm annoyed but I'll live

### Description

this is the first failing run: 
https://github.com/cloudoperators/greenhouse/actions/runs/8601060342
which points to this commit:
https://github.com/cloudoperators/greenhouse/commit/a43ac46e0ee25b71c483d10766c3f0df39f8ebd5

We need to investigate what makes the `docker buildx` fail for the `Dockerfile.dev-env` as the commit does not include changes to either of:

- `./Dockerfile.dev-env`
- `./cmd/dev-env`

### Reproduction steps

```bash
1. Go to https://github.com/cloudoperators/greenhouse/actions/runs/8601060342
2. Check logs for `Build and push Docker Image` step of https://github.com/cloudoperators/greenhouse/actions/runs/8601060342/job/23567388327
```

**Comment by kengou** [comment]
The issue still persist. Going to investigate it further

**Comment by kengou** [comment]
Found the issue: `go: cannot install cross-compiled binaries when GOBIN is set` 
There is an open issue already for that: https://github.com/golang/go/issues/57485

Option's to mitigate the issue:

1. remove `$GOBIN`
2. add `-o` to the go install `go build -o out ...`
