### ISSUE TITLE
Initial Release Preparation

### ISSUE THREAD

**Issue by IvoGoman** [cloudoperators/greenhouse#13]
- [x] container images pushed to Github registry (via GH Actions)
- [x] helm-charts pushed to Github registry (via GH Actions)
- [x] UI container to Github registry (via GH Actions)
- [ ] How-to for installing Greenhouse ( + manual test)
- [ ] add disclaimer that CRDs are `alphav1` and documentation is in-progress to Project readme
- [x] check links from Project readme and documentation are working after repo move
- [ ] (optional) link Greenhouse Documentation from ORA Website

**Comment by IvoGoman** [comment]
There are SAP ID specific steps in the docs: https://github.com/cloudoperators/greenhouse/blob/9d15086ddc2542a589bf8a4707bcdabb57c447f3/docs/getting-started/quick-start.md?plain=1#L16-L27
and 
https://github.com/cloudoperators/greenhouse/blob/9d15086ddc2542a589bf8a4707bcdabb57c447f3/docs/user-guides/organization/creation.md?plain=1#L29-L39

For the initial release the docs should also include steps for a non-SAP IDP

**Comment by kengou** [comment]
@IvoGoman I think we need to name 2-3 alternatives where I can document how to setup.
My proposals are:

- Azure EntraID
- Auth0 / Okta
- Keycloak

**Comment by IvoGoman** [comment]
closing in favour of #590, open topics are migrated/linked
