### ISSUE TITLE
[FEAT] - Readiness for Plugin's workload resources

### ISSUE THREAD

**Issue by IvoGoman** [cloudoperators/greenhouse#185]
### Priority

(Medium)

### Description

> As user of Greenhouse I would like to see the current status of a Plugin in the Dashboard , so that I know if the resources on the remote cluster are up and running. 

Currently there is no visibility into the runtime status of a Plugin's status. If a Plugin's HelmChart is deployed there is no indication if the workload resources actually are up and running.
Workload resources need to be checked if they either completed successfully, the desired replicas are ready, they are on the latest revision or readiness/liveness probes are failing.

Acceptance Criteria:

- [ ] Plugin has an additional statusCondition for the workload readiness
- [ ] The readiness for a `Pod`, `Deployment`, `ReplicaSet`, `StatefulSet`, `DaemonSet`, and `ReplicationController` contained in the Plugins release are checked regularly
- [ ] There is a dedicated Controller for the PluginStatus

**Comment by auhlig** [comment]
@databus23 and I were talking about this.
The rollout status might not be enough since it only reflects exactly that: The status of the last rollout.
However, the workload resources should be continously monitored and configured readiness/liveness probes taken into account. 
This can be achieved by comparing the expected and ready replicas in the status of the {Deployment, StatefulSet, Daemonset}. Note that all 3 contain these status information, however the struct vary slightly

**Comment by IvoGoman** [comment]
The continuous monitoring and comparing of replicas in a workload resource's status sounds redundant to metrics exported by `kube-state-metrics` and alerts such as `KubeStatefulSetReplicasMismatch` which are already part of the `kube-monitoring` plugin.

It would be nice to see the Plugin's status reflect if the workload resources are running. This would require frequent reconciliation of each plugin's status to have the dashboard show current information. I am not sure if this is worth it just to show the status. In most cases (if not all) the Prometheus alert should be the favourable way to indicate that the workload resources are not up.
Instead of implementing this here we could look into integrating our internal setup with `owner-label-injector` to Greenhouse to bring the alerts w.r.t. a Plugin to the people responsible.

**Comment by auhlig** [comment]
> The continuous monitoring and comparing of replicas in a workload resource's status sounds redundant to metrics exported by kube-state-metrics and alerts such as KubeStatefulSetReplicasMismatch which are already part of the kube-monitoring plugin.

The `kube-state-metrics` is an external tool provide as part of a plugin that might or might not be deployed.
Even if it is deployed, it can't monitor itself.
Transparency for the plugins deployed should be a core feature of the platform and IMHO be implemented as such.

> This would require frequent reconciliation of each plugin's status to have the dashboard show current information.

The frequency depends on the implementation though it should be guaranteed it's relatively up to date.

>  In most cases (if not all) the Prometheus alert should be the favourable way to indicate that the workload resources are not up.

IMO a central operations hub should provide transparency on this central aspect. 
Monitoring and alerting capabilities might or might not be deployed and even if they are they can't be used to monitor themselves. This should be done the operations platform and reflected in the plugin status.

**Comment by auhlig** [comment]
> True, but that is something which could be covered by integrating [sapcc/absent-metrics-operator](https://github.com/sapcc/absent-metrics-operator) to ensure that alerts with missing metrics are picked up.

Valid point.
However, it's quite involved and introduces several dependencies (absent-metrics, kube-state-metrics, Prometheus, Alertmanager, Slack, etc.) for the entire monitoring & alerting chain to work. 
While this is a very useful layer, relying on multiple plugins being deployed and working to provide transparency for this core feature would be risky in addition to the mentioned self-monitoring problem.

> My only concern here is that monitoring the replicas does not guarantee that the Plugin as a whole is working.

Fully agree.
Evaluating the readiness and liveness of Kubernetes workload resources that are deployed via plugins is the first pragmatic step to getting some transparency into the platform.
While deploying the kube-monitoring plugin, the platform reported an all green deployed status, while in fact the Prometheus was crashlooping.
Having the readiness and liveness of workload resources reflected in the status offers an interface from Greenhouse side and leaves it to plugin developers to configure meaningful probes.
This would cover the cases we've seen so far.

> The overall working state of the Plugin should be covered by https://github.com/cloudoperators/greenhouse/issues/106, as a Plugin developer will be able to provide specific test cases that ensure the helm release is deployed correctly.

Yes. The Helm tests would be a nice next step for more complex tests. 
We might want to consider evaluating OCM and the landscaper before investing more into Helm specifics.
