### ISSUE TITLE
[FEAT] - Build Website via GitHub Action

### ISSUE THREAD

**Issue by IvoGoman** [cloudoperators/greenhouse#186]
### Priority

(Medium) I'm annoyed but I'll live

### Description

Acceptance Criteria:

- [x] Website is build with Hugo with an Action and published to GitHub pages #174 
- [x] Changes to the Readme's of _PluginDefinitions_ in cloudoperators/greenhouse-extensions trigger the action https://github.com/cloudoperators/greenhouse-extensions/pull/85
- [ ] (optional) It is possible to choose different versions of the docs (e.g. main, vX.Y)

**Comment by auhlig** [comment]
Isn't that done @kengou?

**Comment by kengou** [comment]
> Isn't that done @kengou?

Not yet, the GitHub technical user is pending

> Changes to the Readme's of PluginDefinitions in cloudoperators/greenhouse-extensions trigger the action https://github.com/cloudoperators/greenhouse-extensions/pull/85

**Comment by IvoGoman** [comment]
This is working now: https://github.com/cloudoperators/greenhouse/actions/runs/9125819435
Thanks @kengou 🚀
