### ISSUE TITLE
[FEAT] - Enhance Cluster onboarding process

### ISSUE THREAD

**Issue by IvoGoman** [cloudoperators/greenhouse#190]
### Priority

(Medium) I'm annoyed but I'll live

### Description

tbd

**Comment by auhlig** [comment]
Adding to the wishlist:
- I can onboard a directly connected cluster from the UI and don't require greenhousectl

**Comment by kengou** [comment]
- API endpoint for onboarding / mass onboarding 
- Onboard cluster via kubectl ( no need for `greenhousectl`)

**Comment by IvoGoman** [comment]
closed with #655
