### ISSUE TITLE
chore(setup): create reuseable workflows and build CIs for juno, greenhouse and greenhouse extensions

### ISSUE THREAD

**Issue by edda** [cloudoperators/greenhouse#287]
- [x] build reuseable workflows for:
  - check 3rd party licenses
  - test uni
  - build
  - publish

- [x] build CI for juno
- [x] build CI for greenhouse
- [x] build CI for greenhouse-extensions

Belongs to: https://github.com/cloudoperators/juno/issues/40

**Comment by ArtieReus** [comment]
This workflow is extended to check 3rd party licenses, run tests and build.
