### ISSUE TITLE
[SPIKE] - Frontend development guidelines

### ISSUE THREAD

**Issue by uwe-mayer** [cloudoperators/greenhouse#290]
### Priority

None

### Description
We want to provide guidelines for consistent development of all frontend code: micro frontends, helpers, utilities, etc.
The following aspects (not exclusive!) should be discussed and put into a written guideline
- Typescript usage
- folder structure
- UI best practices
- plugin version pinning (plugin within plugin)
- shared resources ?
- shared state ?
- testing

**Comment by uwe-mayer** [comment]
- Typescript first ToDos:
  - How to publish types for existing libs (e.g. `messages-provider`)
  - Rewrite k8s-client with Typescript
  - Some kind of document

**Comment by edda** [comment]
Replaced by https://github.com/cloudoperators/juno/issues/80
