### ISSUE TITLE
[FEAT] - e2e test for Cluster Bootstrap

### ISSUE THREAD

**Issue by IvoGoman** [cloudoperators/greenhouse#291]
### Priority

(Medium) I'm annoyed but I'll live

### Description

This test ensures that:

- remote cluster can be onboarded
  - differentiate on `USE_EXISTING_CLUSTER`:
    - `false`:  spin Up "remote" envtest controlplane to test against as in [this example](https://github.com/cloudoperators/greenhouse/blob/main/pkg/controllers/suite_test.go#L39)
    - `true`: test against remote cluster specified by kubeconfig located at `TEST_REMOTE_KUBECONFIG`
      - Testrunner can decide wether to run against local `KIND` or existing cluster
- cluster status is reconciled, see [status_controller.go](https://github.com/cloudoperators/greenhouse/blob/main/pkg/controllers/cluster/status_controller.go)
  -  Namely: `kubeConfigValidCondition`, `allNodesReadyCondition`, `readyCondition`, 
- expected resources are present on the remote cluster, mainly see [direct_access_controller.go](https://github.com/cloudoperators/greenhouse/blob/main/pkg/controllers/cluster/direct_access_controller.go)
  - `Cluster` resource present on central Greenhouse Cluster
  - `Namespace` in remote Cluster
  - `SA` in remote Cluster
  - `ClusterRoleBinding` for `SA` in remote Cluster
  - [ServiceAccountToken](https://github.com/cloudoperators/greenhouse/blob/main/pkg/controllers/cluster/util.go#L167)

**Comment by abhijith-darshan** [comment]
> @abhijith-darshan is this implemented with #683? (besides this not referencing the new e2e workflow)

It is doing onboarding via secret and checking if the Cluster resource is created. The only thing missing from a bootstrap perspective is to check for `OwnerReference` on the greenhouse secret.
