### ISSUE TITLE
[FEAT] - e2e test for Cluster lifecycle

### ISSUE THREAD

**Issue by IvoGoman** [cloudoperators/greenhouse#292]
### Priority

(Medium) I'm annoyed but I'll live

### Description

This e2e test ensures that

- remote cluster resource is onboarded
- Plugin deployment to check remote resources
- cluster offboarding
- resources on the remote cluster are removed 
- secret for the cluster is deleted

**Comment by uwe-mayer** [comment]
braindump:
We should test deletion of deployed Plugins in conjunction with cluster deletion doesn't get stuck (we had a case)
- Delete first Plugin then Cluster
- Delete first Cluster then Plugin

**Comment by abhijith-darshan** [comment]
Update:

Deleting cluster will delete the plugins, handled by - https://github.com/cloudoperators/greenhouse/pull/609

The new `KinD` based e2e test for plugin lifecycle will cover plugin deletion checks via cluster off-boarding
