### ISSUE TITLE
🐛 [BUG] - (ui)  watches on unauthorized objects throw constant errors

### ISSUE THREAD

**Issue by edda** [cloudoperators/greenhouse#293]
### Priority

(Medium) I'm annoyed but I'll live

### Description

For users who aren't authorized to get secrets the browser console is spammed with failing watch responses and 403 messages.

Expected behaviour:
If the user isn't authorized to GET secrets the watch shouldn't be initiated

### Reproduction steps

```bash
1. As a user who isn't authorized to GET secrets access the Greenhouse dashboard
2. Open the browser console to see the error spam
```

**Comment by uwe-mayer** [comment]
Boradening context of the issue:
This is not only true for secrets in secrets admin, but it is a general problem.
Depending on the users permissions the client might get unauthorized on getting/watching k8s resources.
We need to correctly handle the errors and safeguard the watches from retrying when unauthorized.
