### ISSUE TITLE
[FEAT] - Configuration possibility to forward controller logs to ElasticSearch

### ISSUE THREAD

**Issue by uwe-mayer** [cloudoperators/greenhouse#485]
### Priority

(Medium) I'm annoyed but I'll live

### Description

We need the possibility to forward Greenhouse Controller logs to an ElasticSearch endpoint for scenarios where we cannot audit log the k8s apiserver (e.g. Greenhouse running on managed k8s cluster)

### Reference Issues

https://github.com/cloudoperators/greenhouse/issues/388

**Comment by IvoGoman** [comment]
Implemented in https://github.com/cloudoperators/greenhouse-extensions/pull/375 and #528

Message is not yet parsed, as I need some advice from @Kuckkuck once he is back next week.
