### ISSUE TITLE
[REFAC] - Merge & Standardize  DirectAccess-, and ClusterStatusController

### ISSUE THREAD

**Issue by IvoGoman** [cloudoperators/greenhouse#579]
Currently there are 3 controllers which are reconciling the `Cluster` resource. As part of the Standardisation of the Reconciliation Loop of Greenhouse controllers these controllers should be merged into a single one. 

## Acceptance Criteria

- [x] There is one `ClusterController` 
- [x] The controller can update DirectAccess clusters, but does not run the logic for `HeadScaleAccess`
- [x] The controller updates the status of the `Cluster`
- [x] HeadscaleController is not to be touched

**Comment by abhijith-darshan** [comment]
Update: `HeadScale` was removed in this PR https://github.com/cloudoperators/greenhouse/pull/635

**Comment by IvoGoman** [comment]
I have moved the removal of finalizers, to be tracked for all controllers.
