### ISSUE TITLE
[REFAC] - Standardise Organisation controllers

### ISSUE THREAD

**Issue by IvoGoman** [cloudoperators/greenhouse#583]
As part of the standardisation of the reconciliation loop for Greenhouse controllers, these controllers need to be updated to follow the common recommendation for the Reconciliation. This includes DexController, OrganizationController, RBACController, ServiceProxyController, TeamRoleSeederController. 

It is not required to consolidate these controllers at this point.

## Acceptance Criteria

- [ ] Implement the Interface
- [ ] Use the standardised patch for updating the status instead of the deferred update (if applicable)
- [ ] Convert the tests to use [test.TestSetup](https://github.com/cloudoperators/greenhouse/blob/main/pkg/test/resources.go) (if applicable) including creation of missing resources 
- [ ] Remove dedicated finalizers used on the controllers because they are replaced with standard ones.

**Comment by uwe-mayer** [comment]
possible duplication: https://github.com/cloudoperators/greenhouse/issues/414
