### ISSUE TITLE
🐛 [BUG] - TeamMembershipUpdater error out if no members are found for Team

### ISSUE THREAD

**Issue by IvoGoman** [cloudoperators/greenhouse#812]
### Priority

(Medium) I'm annoyed but I'll live

### Description

With #794 the Members of a Team are added to it's Status, additionally to having them in the TeamMembership resource.
The field `.status.members` is a required field but never initialized. This results in the controller failing to update the Team's status in case there is an error retrieving the members.

> Reconciler error	{"controller": "teamMembershipUpdater", "controllerGroup": "greenhouse.sap", "controllerKind": "Team", "Team": {"name":"demo","namespace":"demo"}, "namespace": "demo", "name": "demo", "reconcileID": "43b8dd6a-5997-4f24-a9a4-8ada7d8a7e9f", "error": "Team.greenhouse.sap \"demo\" is invalid: members: Required value"}

Instead the list of members should be initialized to an empty slice in case it does not yet exist in the status.

### Reproduction steps

```bash
1. Create a Team where there are no members to be fetched from SCIM
2. Team's status will not be updated
3. See error in controller logs
```

### Manifests

```yaml
apiVersion: greenhouse.sap/v1alpha1
  kind: ...
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by gciezkowski-acc** [comment]
Fixed by @abhijith-darshan in PR: https://github.com/cloudoperators/greenhouse/pull/814
